# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7409_mac_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7409_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7409_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7409_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7409_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7409_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7409_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7409_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
