#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : pass_through.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed May 25 16:23:37 CEST 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved. 
#
# usage: pass_through.sh [-help]
# usage: pass_through.sh [-lib_map_path]
# usage: pass_through.sh [-noclean_files]
# usage: pass_through.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'pass_through.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_11 processing_system7_vip_v1_0_13 xil_defaultlib axi_lite_ipif_v3_0_4 axi_ethernet_buffer_v2_0_24 xbip_utils_v3_0_10 xbip_pipe_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_17 tri_mode_ethernet_mac_v9_0_20 c_reg_fd_v12_0_6 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_14 xlconstant_v1_1_7 util_vector_logic_v2_0_1 lib_pkg_v1_0_2 fifo_generator_v13_2_6 lib_fifo_v1_0_15 axi_fifo_mm_s_v4_2_7 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_25 axi_data_fifo_v2_1_24 axi_crossbar_v2_1_26 axi_protocol_converter_v2_1_25 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "pass_through.sh - Script generated by export_simulation (Vivado v2021.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/tools/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_11 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/63b7/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_processing_system7_0_0/sim/pass_through_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_ethernet_buffer_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/1ed2/hdl/axi_ethernet_buffer_v2_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_0/sim/bd_7409_eth_buf_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_17 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/dd36/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work tri_mode_ethernet_mac_v9_0_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/f6d4/hdl/tri_mode_ethernet_mac_v9_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work tri_mode_ethernet_mac_v9_0_20 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/f6d4/hdl/tri_mode_ethernet_mac_v9_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/common/bd_7409_mac_0_block_reset_sync.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/common/bd_7409_mac_0_block_sync_block.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_axi4_lite_ipif_top.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_axi4_lite_ipif_wrapper.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/physical/bd_7409_mac_0_gmii_if.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_tx_clk_gen.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/statistics/bd_7409_mac_0_vector_decode.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_block.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_support.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0_support_resets.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_7409_mac_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/2598/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_2/sim/bd_7409_c_shift_ram_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/7161/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/9ac8/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/1f12/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_3/sim/bd_7409_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_4/sim/bd_7409_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3f90/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_5/sim/bd_7409_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/sim/bd_7409.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_1/sim/pass_through_axi_ethernet_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/8ae1/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_6 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/8ae1/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/8ae1/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_15 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/a4ed/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_fifo_mm_s_v4_2_7 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/7665/hdl/axi_fifo_mm_s_v4_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_fifo_0/sim/pass_through_axi_ethernet_0_fifo_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1_clk_wiz.v" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/e1e6/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/fa53/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ac57/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_xbar_0/sim/pass_through_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/8fe4/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_auto_pc_0/sim/pass_through_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pass_through/ip/pass_through_rst_ps7_0_100M_1/sim/pass_through_rst_ps7_0_100M_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../ethernet_pass_through.gen/sources_1/bd/pass_through/ipshared/62b6" +incdir+"/tools/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/pass_through/sim/pass_through.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.pass_through xil_defaultlib.glbl -o pass_through_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./pass_through_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./pass_through.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key pass_through_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc pass_through_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./pass_through.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: pass_through.sh [-help]\n\
Usage: pass_through.sh [-lib_map_path]\n\
Usage: pass_through.sh [-reset_run]\n\
Usage: pass_through.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
