# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.srcs/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1.xci
# IP: The module: 'pass_through_axi_ethernet_0_refclk_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_refclk_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_refclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_refclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.srcs/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1.xci
# IP: The module: 'pass_through_axi_ethernet_0_refclk_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_refclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_refclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_refclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
