# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.srcs/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/pass_through_axi_ethernet_0_1.xci
# IP: The module: 'pass_through_axi_ethernet_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/bd_7409.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409 || ORIG_REF_NAME==bd_7409} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_0/bd_7409_eth_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_eth_buf_0 || ORIG_REF_NAME==bd_7409_eth_buf_0} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/bd_7409_mac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_mac_0 || ORIG_REF_NAME==bd_7409_mac_0} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_2/bd_7409_c_shift_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_c_shift_ram_0_0 || ORIG_REF_NAME==bd_7409_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_3/bd_7409_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_c_counter_binary_0_0 || ORIG_REF_NAME==bd_7409_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_4/bd_7409_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_xlconstant_0_0 || ORIG_REF_NAME==bd_7409_xlconstant_0_0} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_5/bd_7409_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_util_vector_logic_0_0 || ORIG_REF_NAME==bd_7409_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/bd_7409_ooc.xdc

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/pass_through_axi_ethernet_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/synth/pass_through_axi_ethernet_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/synth/pass_through_axi_ethernet_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.srcs/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/pass_through_axi_ethernet_0_1.xci
# IP: The module: 'pass_through_axi_ethernet_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/bd_7409.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409 || ORIG_REF_NAME==bd_7409} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_0/bd_7409_eth_buf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_eth_buf_0 || ORIG_REF_NAME==bd_7409_eth_buf_0} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_1/bd_7409_mac_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_mac_0 || ORIG_REF_NAME==bd_7409_mac_0} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_2/bd_7409_c_shift_ram_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_c_shift_ram_0_0 || ORIG_REF_NAME==bd_7409_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_3/bd_7409_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_c_counter_binary_0_0 || ORIG_REF_NAME==bd_7409_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_4/bd_7409_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_xlconstant_0_0 || ORIG_REF_NAME==bd_7409_xlconstant_0_0} -quiet] -quiet

# IP: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/ip/ip_5/bd_7409_util_vector_logic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7409_util_vector_logic_0_0 || ORIG_REF_NAME==bd_7409_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/bd_0/bd_7409_ooc.xdc

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/pass_through_axi_ethernet_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/synth/pass_through_axi_ethernet_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/ip/pass_through_axi_ethernet_0_1/synth/pass_through_axi_ethernet_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pass_through_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
