# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pass_through/pass_through.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pass_through || ORIG_REF_NAME==pass_through} -quiet] -quiet

# IP: bd/pass_through/ip/pass_through_processing_system7_0_0/pass_through_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pass_through_processing_system7_0_0 || ORIG_REF_NAME==pass_through_processing_system7_0_0} -quiet] -quiet

# IP: bd/pass_through/ip/pass_through_axi_ethernet_0_1/pass_through_axi_ethernet_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pass_through_axi_ethernet_0_1 || ORIG_REF_NAME==pass_through_axi_ethernet_0_1} -quiet] -quiet

# IP: bd/pass_through/ip/pass_through_axi_ethernet_0_fifo_0/pass_through_axi_ethernet_0_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pass_through_axi_ethernet_0_fifo_0 || ORIG_REF_NAME==pass_through_axi_ethernet_0_fifo_0} -quiet] -quiet

# IP: bd/pass_through/ip/pass_through_axi_ethernet_0_refclk_1/pass_through_axi_ethernet_0_refclk_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pass_through_axi_ethernet_0_refclk_1 || ORIG_REF_NAME==pass_through_axi_ethernet_0_refclk_1} -quiet] -quiet

# IP: bd/pass_through/ip/pass_through_xbar_0/pass_through_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pass_through_xbar_0 || ORIG_REF_NAME==pass_through_xbar_0} -quiet] -quiet

# IP: bd/pass_through/ip/pass_through_auto_pc_0/pass_through_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pass_through_auto_pc_0 || ORIG_REF_NAME==pass_through_auto_pc_0} -quiet] -quiet

# IP: bd/pass_through/ip/pass_through_ps7_0_axi_periph_1/pass_through_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pass_through_ps7_0_axi_periph_1 || ORIG_REF_NAME==pass_through_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/pass_through/ip/pass_through_rst_ps7_0_100M_1/pass_through_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pass_through_rst_ps7_0_100M_1 || ORIG_REF_NAME==pass_through_rst_ps7_0_100M_1} -quiet] -quiet

# XDC: /home/jonathanb/VivadoProjects/ethernet_pass_through/ethernet_pass_through.gen/sources_1/bd/pass_through/pass_through_ooc.xdc
